export const leaderBoardDummyData = [
  {
    rank: 1,
    username: 'afrmn649',
    level: 45,
    xp: 1082055,
    gold: 140,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 2,
    username: 'jnico198',
    level: 45,
    xp: 558162,
    gold: 22513,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: true,
  },
  {
    rank: 3,
    username: 'lavio707',
    level: 44,
    xp: 985024,
    gold: 3392,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 4,
    username: 'smeric452',
    level: 41,
    xp: 738896,
    gold: 30784,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 5,
    username: 'fish_whisperer925',
    level: 41,
    xp: 723233,
    gold: 11352,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 6,
    username: 'rex68',
    level: 40,
    xp: 688425,
    gold: 0,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 7,
    username: 'nexckycort225',
    level: 39,
    xp: 612304,
    gold: 28995,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 8,
    username: 'nullpointersam689',
    level: 38,
    xp: 565867,
    gold: 12575,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 9,
    username: 'davidgonzalez265',
    level: 37,
    xp: 516102,
    gold: 7988,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 10,
    username: 'josephrdev21376',
    level: 36,
    xp: 426353,
    gold: 2934,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 11,
    username: 'steven009r830',
    level: 36,
    xp: 446502,
    gold: 634,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 12,
    username: 'doit353',
    level: 32,
    xp: 265447,
    gold: 352,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 13,
    username: 'alexa_lal933',
    level: 32,
    xp: 287280,
    gold: 242,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 14,
    username: 'andrescampuzano999',
    level: 31,
    xp: 244911,
    gold: 29056,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 15,
    username: 'brycot177',
    level: 30,
    xp: 196114,
    gold: 16569,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 16,
    username: 'deltadax728',
    level: 30,
    xp: 199544,
    gold: 3796,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 17,
    username: 'sergepin950',
    level: 30,
    xp: 527504,
    gold: 2597,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 18,
    username: 'dandheedge372',
    level: 29,
    xp: 172275,
    gold: 61066,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 19,
    username: 'georgie949',
    level: 29,
    xp: 189173,
    gold: 37140,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 20,
    username: 'dawfyd197',
    level: 28,
    xp: 156920,
    gold: 42,
    fishEmojis: '🛳️🛳️',
    emojiDescription: 'A commercial fleet of fish',
    isInfected: false,
  },
  {
    rank: 21,
    username: 'ronlabdev331',
    level: 24,
    xp: 76220,
    gold: 4446,
    fishEmojis: '🛳️🛳️',
    emojiDescription: 'A commercial fleet of fish',
    isInfected: false,
  },
  {
    rank: 22,
    username: 'andrestheran980',
    level: 24,
    xp: 81037,
    gold: 569,
    fishEmojis: '🛳️🛳️',
    emojiDescription: 'A commercial fleet of fish',
    isInfected: false,
  },
  {
    rank: 23,
    username: 'tatd3v633',
    level: 21,
    xp: 38574,
    gold: 1713,
    fishEmojis: '🚢🚢',
    emojiDescription: 'A small fleet of fish',
    isInfected: false,
  },
  {
    rank: 24,
    username: 'achuryds269',
    level: 20,
    xp: 33353,
    gold: 9460,
    fishEmojis: '🛳️🛳️',
    emojiDescription: 'A commercial fleet of fish',
    isInfected: false,
  },
  {
    rank: 25,
    username: 'rex827',
    level: 19,
    xp: 5822,
    gold: 4780,
    fishEmojis: '🚢🚢',
    emojiDescription: 'A small fleet of fish',
    isInfected: false,
  },
  {
    rank: 26,
    username: 'choquito205',
    level: 19,
    xp: 22416,
    gold: 1173,
    fishEmojis: '🚢🚢',
    emojiDescription: 'A small fleet of fish',
    isInfected: false,
  },
  {
    rank: 27,
    username: 'jgvilchezc950',
    level: 19,
    xp: 21565,
    gold: 5222,
    fishEmojis: '🛳️🛳️',
    emojiDescription: 'A commercial fleet of fish',
    isInfected: false,
  },
  {
    rank: 28,
    username: 'andresmarulandam512',
    level: 18,
    xp: 19452,
    gold: 6084,
    fishEmojis: '🚢🚢',
    emojiDescription: 'A small fleet of fish',
    isInfected: false,
  },
  {
    rank: 29,
    username: 'jhosuacode698',
    level: 17,
    xp: 13257,
    gold: 15786,
    fishEmojis: '🚢🚢',
    emojiDescription: 'A small fleet of fish',
    isInfected: false,
  },
  {
    rank: 30,
    username: 'juanfrank77120',
    level: 17,
    xp: 12354,
    gold: 4684,
    fishEmojis: '🚢🚢',
    emojiDescription: 'A small fleet of fish',
    isInfected: false,
  },
  {
    rank: 31,
    username: 'rex259',
    level: 15,
    xp: 7550,
    gold: 1485,
    fishEmojis: '🛳️',
    emojiDescription: 'A passenger ship of fish',
    isInfected: false,
  },
  {
    rank: 32,
    username: 'aizcream430',
    level: 15,
    xp: 365132,
    gold: 50525,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 33,
    username: 'sp1r1t629',
    level: 15,
    xp: 2066,
    gold: 546,
    fishEmojis: '🚢',
    emojiDescription: 'A shipload of fish',
    isInfected: false,
  },
  {
    rank: 34,
    username: 'valenrobledo31616',
    level: 15,
    xp: 6061,
    gold: 4077,
    fishEmojis: '⚓',
    emojiDescription: 'Enough fish to drop anchor',
    isInfected: false,
  },
  {
    rank: 35,
    username: 'smmdigitaldreams249',
    level: 15,
    xp: 1802,
    gold: 954,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 36,
    username: 'ntw530',
    level: 12,
    xp: 566,
    gold: 816,
    fishEmojis: '🚢',
    emojiDescription: 'A shipload of fish',
    isInfected: false,
  },
  {
    rank: 37,
    username: 'leclaire770',
    level: 8,
    xp: 1264,
    gold: 4925,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 38,
    username: 'maoacr892',
    level: 7,
    xp: 240,
    gold: 29153,
    fishEmojis: '🚢🚢',
    emojiDescription: 'A small fleet of fish',
    isInfected: false,
  },
  {
    rank: 39,
    username: 'yercas93458',
    level: 5,
    xp: 276,
    gold: 1985,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 40,
    username: 'therealtaim599',
    level: 4,
    xp: 171,
    gold: 4663,
    fishEmojis: '🛳️',
    emojiDescription: 'A passenger ship of fish',
    isInfected: false,
  },
  {
    rank: 41,
    username: 'dandheedge861',
    level: 3,
    xp: 368,
    gold: 30997,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 42,
    username: 'rex156',
    level: 2,
    xp: 146,
    gold: 3411,
    fishEmojis: '🛳️',
    emojiDescription: 'A passenger ship of fish',
    isInfected: false,
  },
  {
    rank: 43,
    username: 'dandheedge822',
    level: 2,
    xp: 188,
    gold: 683,
    fishEmojis: '⛵',
    emojiDescription: 'A sailboat of fish',
    isInfected: false,
  },
  {
    rank: 44,
    username: 'admin',
    level: 1,
    xp: 0,
    gold: 19700,
    fishEmojis: '🚣',
    emojiDescription: 'A boatload of fish',
    isInfected: false,
  },
  {
    rank: 45,
    username: 'tester',
    level: 1,
    xp: 0,
    gold: 4,
    fishEmojis: '🚣',
    emojiDescription: 'A boatload of fish',
    isInfected: false,
  },
  {
    rank: 46,
    username: 's0c5794',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 47,
    username: 's0c5757',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 48,
    username: 'drwho837',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 49,
    username: 'julilove338',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 50,
    username: 'carlosaroca880',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 51,
    username: 'carlosaroca745',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 52,
    username: 'carlosaroca424',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 53,
    username: 'carlosaroca133',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 54,
    username: 'carlosaroca649',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 55,
    username: 'carlosaroca273',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 56,
    username: 'carlosaroca117',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 57,
    username: 'carlosaroca473',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 58,
    username: 'carlosaroca384',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 59,
    username: 'carlosaroca817',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 60,
    username: 'carlosaroca828',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 61,
    username: 'carlosaroca369',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 62,
    username: 'carlosaroca328',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 63,
    username: 'carlosaroca189',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 64,
    username: 'carlosaroca809',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 65,
    username: 'carlosaroca511',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 66,
    username: 'carlosaroca195',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 67,
    username: 'carlosaroca617',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 68,
    username: 'carlosaroca786',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 69,
    username: 'carlosaroca183',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 70,
    username: 'carlosaroca827',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 71,
    username: 'carlosaroca17',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 72,
    username: 'carlosaroca31',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 73,
    username: 'carlosaroca119',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 74,
    username: 'carlosaroca976',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 75,
    username: 'carlosaroca632',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 76,
    username: 'carlosaroca25',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 77,
    username: 'carlosaroca170',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 78,
    username: 'carlosaroca232',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 79,
    username: 'carlosaroca94',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 80,
    username: 'carlosaroca81',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 81,
    username: 'carlosaroca925',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 82,
    username: 'carlosaroca483',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 83,
    username: 'carlosaroca968',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 84,
    username: 'carlosaroca759',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 85,
    username: 'carlosaroca936',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 86,
    username: 'carlosaroca111',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 87,
    username: 'carlosaroca486',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 88,
    username: 'carlosaroca161',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 89,
    username: 'carlosaroca104',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 90,
    username: 'carlosaroca399',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 91,
    username: 'carlosaroca301',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 92,
    username: 'carlosaroca99',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 93,
    username: 'carlosaroca527',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 94,
    username: 'carlosaroca28',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 95,
    username: 'carlosaroca804',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 96,
    username: 'carlosaroca413',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 97,
    username: 'carlosaroca388',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 98,
    username: 'gueri360929',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 99,
    username: 'gueri360745',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 100,
    username: 'gueri360404',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 101,
    username: 'gueri360663',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 102,
    username: 'gueri360496',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 103,
    username: 'gueri360388',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 104,
    username: 'gueri360107',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 105,
    username: 'gueri360597',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 106,
    username: 'gueri360750',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 107,
    username: 'gueri360132',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 108,
    username: 'gueri360562',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 109,
    username: 'gueri360591',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 110,
    username: 'gueri360400',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 111,
    username: 'gueri360164',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 112,
    username: 'gueri360906',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 113,
    username: 'gueri360943',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 114,
    username: 'gueri360892',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 115,
    username: 'gueri360432',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 116,
    username: 'gueri360100',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 117,
    username: 'gueri360725',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 118,
    username: 'gueri360363',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 119,
    username: 'gueri360350',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 120,
    username: 'gueri360135',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 121,
    username: 'gueri36083',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 122,
    username: 'gueri360552',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 123,
    username: 'gueri360682',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 124,
    username: 'gueri360856',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 125,
    username: 'gueri360760',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 126,
    username: 'gueri360338',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 127,
    username: 'gueri360797',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 128,
    username: 'gueri360779',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 129,
    username: 'gueri360347',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 130,
    username: 'gueri360122',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 131,
    username: 'gueri360364',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 132,
    username: 'gueri360216',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 133,
    username: 'gueri360136',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 134,
    username: 'gueri360775',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 135,
    username: 'gueri360479',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 136,
    username: 'gueri360197',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 137,
    username: 'gueri36043',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 138,
    username: 'gueri36074',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 139,
    username: 'gueri360345',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 140,
    username: 'gueri360608',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 141,
    username: 'gueri360974',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 142,
    username: 'gueri360417',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 143,
    username: 'gueri360627',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 144,
    username: 'gueri360382',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 145,
    username: 'gueri360384',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 146,
    username: 'gueri360247',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 147,
    username: 'rex731',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 148,
    username: 'rex359',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 149,
    username: 'rex578',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 150,
    username: 'rex463',
    level: 1,
    xp: 0,
    gold: 105,
    fishEmojis: '🐋 ····',
    emojiDescription: 'A decent catch',
    isInfected: false,
  },
  {
    rank: 151,
    username: 'rex50',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 152,
    username: 'rex630',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 153,
    username: 'rex319',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 154,
    username: 'rex930',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 155,
    username: 'rex369',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 156,
    username: 'rex937',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 157,
    username: 'rex769',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 158,
    username: 'rex94',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 159,
    username: 'rex486',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 160,
    username: 'rex798',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 161,
    username: 'rex236',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 162,
    username: 'rex270',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 163,
    username: 'rex817',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 164,
    username: 'rex445',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 165,
    username: 'rex893',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 166,
    username: 'rex479',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 167,
    username: 'rex822',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 168,
    username: 'rex601',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 169,
    username: 'rex525',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 170,
    username: 'rex372',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 171,
    username: 'rex603',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 172,
    username: 'rex683',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 173,
    username: 'rex503',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 174,
    username: 'rex760',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 175,
    username: 'rex220',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 176,
    username: 'rex205',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 177,
    username: 'rex629',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 178,
    username: 'rex219',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 179,
    username: 'rex669',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 180,
    username: 'rex861',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 181,
    username: 'rex928',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 182,
    username: 'gueri360293',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 183,
    username: 'gueri360359',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 184,
    username: 'gueri360692',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 185,
    username: 'gueri360483',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 186,
    username: 'gueri360434',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 187,
    username: 'gueri360875',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 188,
    username: 'gueri360554',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 189,
    username: 'gueri36020',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 190,
    username: 'gueri36062',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 191,
    username: 'gueri360210',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 192,
    username: 'gueri360801',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 193,
    username: 'gueri3607',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 194,
    username: 'gueri360602',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 195,
    username: 'gueri360495',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 196,
    username: 'gueri360772',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 197,
    username: 'gueri360485',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 198,
    username: 'gueri36042',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 199,
    username: 'gueri360850',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 200,
    username: 'gueri360454',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 201,
    username: 'gueri360681',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 202,
    username: 'gueri360117',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 203,
    username: 'gueri36086',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 204,
    username: 'gueri36019',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 205,
    username: 'gueri360459',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 206,
    username: 'gueri36012',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 207,
    username: 'gueri360612',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 208,
    username: 'gueri360101',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 209,
    username: 'gueri360986',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 210,
    username: 'gueri360798',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 211,
    username: 'gueri360240',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 212,
    username: 'gueri360423',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 213,
    username: 'gueri360224',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 214,
    username: 'gueri360541',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 215,
    username: 'gueri360322',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 216,
    username: 'gueri360519',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 217,
    username: 'gueri360477',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 218,
    username: 'gueri360866',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 219,
    username: 'gueri360657',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 220,
    username: 'gueri360717',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 221,
    username: 'gueri360849',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 222,
    username: 'gueri360258',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 223,
    username: 'gueri360818',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 224,
    username: 'gueri360992',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 225,
    username: 'gueri360803',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 226,
    username: 'gueri360564',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 227,
    username: 'gueri360614',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 228,
    username: 'gueri360928',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 229,
    username: 'gueri360250',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 230,
    username: 'gueri36080',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 231,
    username: 'mellobk454',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 232,
    username: 'dandheedge774',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 233,
    username: 'dandheedge529',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 234,
    username: 'teamo419',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 235,
    username: 'laviladev213',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 236,
    username: 'laviladev533',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 237,
    username: 'carlosaroca350',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 238,
    username: 'rex977',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 239,
    username: 'sirriuz472',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 240,
    username: 'mellobk177',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 241,
    username: 'julio274',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 242,
    username: 'hoid573',
    level: 1,
    xp: 0,
    gold: 178148,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 243,
    username: 'fatchicken277472',
    level: 1,
    xp: 37,
    gold: 10079,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 244,
    username: 'test_user556486',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 245,
    username: 'valenrobledo31477',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 246,
    username: 'pmnightmare589',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 247,
    username: 'josephrdev213160',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 248,
    username: 'felandresj131',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 249,
    username: 'soad733',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 250,
    username: 'andresinho711',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 251,
    username: 'voltaire212945',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 252,
    username: 'thevallejoshow267',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 253,
    username: 'hfoxh662',
    level: 1,
    xp: 0,
    gold: 6739,
    fishEmojis: '🛳️',
    emojiDescription: 'A passenger ship of fish',
    isInfected: false,
  },
  {
    rank: 254,
    username: 'mashu244',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 255,
    username: 'mashu877',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 256,
    username: 'ivandev500',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 257,
    username: 'yeffsolarte600',
    level: 1,
    xp: 0,
    gold: 1349,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 258,
    username: 'peterv924',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 259,
    username: 'amingomezd635',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 260,
    username: 'dandev35789',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 261,
    username: 'astrologicalboy378',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 262,
    username: 'astrologicalboy19',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 263,
    username: 'matthew_idrovo592',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 264,
    username: 'chrrrrrrris152',
    level: 1,
    xp: 0,
    gold: 479,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 265,
    username: 'yurany917',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 266,
    username: 'shelvinbatista819',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 267,
    username: 'asterdev742',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 268,
    username: 'kaiser284454',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 269,
    username: 'juandavid7425',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 270,
    username: 'juanpablohme472',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 271,
    username: 'jpjuliao510',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 272,
    username: 'dandrevielma51',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 273,
    username: 'nanoaxd83171',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 274,
    username: 'robertocarlero332',
    level: 1,
    xp: 0,
    gold: 19713,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
  {
    rank: 275,
    username: 'ido973',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 276,
    username: 'ncondes335',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 277,
    username: 'yersonargote326',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 278,
    username: 'colandru237',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 279,
    username: 'sgarcia710707',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 280,
    username: 'cfcode92643',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 281,
    username: 'andresgutierrez630',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 282,
    username: 'alejok812',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '🐟',
    emojiDescription: 'A small catch of 1 fish',
    isInfected: false,
  },
  {
    rank: 283,
    username: 'jabaku881',
    level: 1,
    xp: 0,
    gold: 0,
    fishEmojis: '',
    emojiDescription: 'No fish caught yet',
    isInfected: false,
  },
  {
    rank: 284,
    username: 'santimondragon116',
    level: 1,
    xp: 52,
    gold: 3833,
    fishEmojis: '🚢🚢🚢 🌊',
    emojiDescription: 'An ocean of fish',
    isInfected: false,
  },
]

export const marketDummyData = {
  items: [
    {
      id: 'b0a227ed-2faa-4fcd-a6ba-5a0dac23d2c2',
      name: 'Enhanced Fishing Rod',
      type: 'fishing_rod',
      description: 'Increases chance of catching rare fish',
      cost: 10000,
    },
    {
      id: 'd86c46bc-c021-42eb-8126-e897c61f7f28',
      name: 'Poison of Leveling',
      type: 'poison_leveling',
      description:
        'PERMANENTLY steals a level and XP from another player (also increases fishing interval by 30s)',
      cost: 250000,
    },
    {
      id: '29c65f9b-4855-4b94-9fe9-4f57316259c5',
      name: 'Poison of Delay',
      type: 'poison_delay',
      description: "Increases another player's fishing interval by 30s (stacks up to 5 minutes)",
      cost: 3000,
    },
    {
      id: '263ed5a4-9ebd-42ba-b4cc-0bbd7d3a79a5',
      name: 'Poison of Recovery',
      type: 'poison_recovery',
      description: 'Reduces fishing interval by 30s (used to recover from poisoning)',
      cost: 5000,
    },
    {
      id: 'a53ff287-89b9-4c33-8edd-6d15b04f0e4e',
      name: 'Poison of Delay',
      type: 'poison_delay',
      description: "Increases another player's fishing interval by 30s (stacks up to 5 minutes)",
      cost: 5000,
    },
    {
      id: '45c7ae69-8d40-402e-9e58-a543186ac8d0',
      name: 'Poison of Reveal Fishes',
      type: 'poison_reveal_fishes',
      description: 'Reveals all fishes in the game',
      cost: 5000,
    },
  ],
}
